[build]
builder = "nixpacks"
buildCommand = "NODE_ENV=development npm install && npx prisma generate && npm run build"

[deploy]
preDeployCommand = "npx prisma migrate deploy"
startCommand = "npm run start"
healthcheckPath = "/api/v1/integrations/africas-talking/status"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
