[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && npx prisma generate"

[deploy]
preDeployCommand = "npx prisma migrate deploy"
startCommand = "npm run start"
healthcheckPath = "/api/v1/integrations/africas-talking/status"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
